
data:
  name: "ECHONET"
  root_dir: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic"
  split_dir: "" 
  nifti_dir: ""
  img_size: [112, 112]
  num_classes: 2
  stratify_bins: [0, 45, 100]

  # name: "VAEUNet" # Default
  # VAEUNet params
  spatial_dims: 2
  in_channels: 1
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  latent_dim: 256
  
  # R2Plus1D params
  # name: "R2Plus1D"
  clip_length: 32

training:
  epochs: 50
  batch_size_train: 64
  batch_size_val: 64
  num_workers: 4
  persistent_workers: True
  lr: 3.0e-4
  weight_decay: 1.0e-4
  kl_weight: 1.0e-4
  patience: 10
  seed: 42
  ckpt_save_path: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet/best_echonet.pt"
  save_dir: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet"
  test_metrics_csv: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet/echonet_metrics.csv"
  clinical_pairs_csv: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet/echonet_clinical_pairs.csv"
