model:
  name: "r2plus1d"
data:
  name: "echonet"
  subset_size: 50

training:
  epochs: 50
  batch_size_train: 16
  batch_size_val: 16
  num_workers: 4
  persistent_workers: True
  lr: 3.0e-4
  weight_decay: 1.0e-4
  kl_weight: 1.0e-4
  patience: 10
  seed: 42
  checkpoint_dir: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/checkpoints"
  save_dir: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet"
  test_metrics_csv: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet/echonet_metrics.csv"
  clinical_pairs_csv: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic/runs/echonet/echonet_clinical_pairs.csv"

tta:
  enabled: true
  lr: 0.0001
  n_augments: 4
  steps: 1
  optimizer: "SGD"
