data:
  root_dir: "/content/drive/MyDrive/Dataset/CAMUS"
  nifti_dir: "/content/drive/MyDrive/Dataset/CAMUS/database_nifti"
  split_dir: "/content/drive/MyDrive/Dataset/CAMUS/database_split"
  img_size: [256, 256]
  num_classes: 4
  stratify_bins: [0, 45, 100]

training:
  epochs: 100
  batch_size_train: 32
  batch_size_val: 32
  lr: 3.0e-4
  weight_decay: 1.0e-4
  patience: 10
  seed: 42
  ckpt_save_path: "best_camus.pt"
  test_metrics_csv: "camus_test_metrics.csv"

model:
  spatial_dims: 2
  in_channels: 1
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2