name: "CAMUS"
root_dir: "/content/drive/MyDrive/Dataset/CAMUS"
nifti_dir: "/content/drive/MyDrive/Dataset/CAMUS/database_nifti"
split_dir: "/content/drive/MyDrive/Dataset/CAMUS/database_split"
img_size: [256, 256]
num_classes: 4
stratify_bins: [0, 45, 100]
