name: "ECHONET"
root_dir: "/content/drive/MyDrive/Dataset/EchoNet-Dynamic"
# root_dir: "datasets/echonet-dynamic"
split_dir: ""
nifti_dir: ""
img_size: [112, 112]
num_classes: 1
stratify_bins: [0, 45, 100]
return_keypoints: true